[build]
  command = "npm run build"
  publish = "out"
  functions = "functions"

[[redirects]]
  from = "/api/rooms"
  to = "https://crew.daily.co/v1/rooms"
  status = 200
  force = true
  headers = {Authorization = "Bearer DAILY_API_KEY_PLACEHOLDER"}

[[plugins]]
  package = "@netlify/plugin-nextjs"