[build]
  command = "sed -i "s|DAILY_API_KEY_PLACEHOLDER|${PROD_API_LOCATION}|g" netlify.toml && npm run build"
  publish = "out"
  functions = "functions"

[[redirects]]
  from = "/api/rooms"
  to = "https://api.daily.co/v1/rooms"
  status = 200
  force = true
  headers = {Authorization = "Bearer DAILY_API_KEY_PLACEHOLDER"}

[[plugins]]
  package = "@netlify/plugin-nextjs"